### ISSUE TITLE
Metroid II Sprite Issues

### ISSUE THREAD

**Issue by tutifrutas** [Jonazan2/PatBoy#8]
Hi,
In Metroid II samus sprite is not rendered, i believe that the issue is the way the rending calculates that a sprite should be shown or not above the background. It compares against the color white, but it should be comparing against the color number 0 instead, since in this game the color 0 is black

**Comment by Jonazan2** [comment]
Thanks for pointing out the issue! The sprites are rendering properly after the fix.

<img width="401" alt="metroid" src="https://user-images.githubusercontent.com/1785204/53917655-f8fcd980-405c-11e9-9d98-0f6b44fef506.png">

Cheers.
