### ISSUE TITLE
main method is missing, and main.cpp is excluded in .gitconfig

### ISSUE THREAD

**Issue by thezerobit** [Jonazan2/PatBoy#9]
I was able to construct a CMake file to build this in Linux, but there is no entry point main() method defined anywhere, and the first line in .gitignore excludes main.cpp, which is concerning. I am very interested in this emulator and I'd love to be able to try it out.

**Comment by Jonazan2** [comment]
Hi,

In order to create an instance of the emulator in main.cpp, include the GameBoy.h class, create a GameBoy object and call StartEmulation(). I will try to submit the main file as soon as possible.
